### ISSUE TITLE
Wrong date selection

### ISSUE THREAD

**Issue by alaaghribi** [distefam/MDCalendar#7]
I've been testing your library to integrate it into my project, and I'd like to thank you for your great effort. However, there is a small bug: when you select a date, let's say July 5, I have July 4 that is selected. In every selection, the PREVIOUS day is selected.
- (void)calendarView:(MDCalendar *)calendarView didSelectDate:(NSDate *)date {
  NSLog(@"date %@",date); //here date is logged with the previous day
  }

Can you please check that ?

Thank you.

**Comment by distefam** [comment]
Thanks for the feedback! Basically, `NSDate` objects simply represent an absolute instant in time from a reference date, which is based on GMT. The log method I had there that you referenced was simply printing the default representation of that date, which was showing the GMT date. I'm assuming your system time-zone was producing a date that appeared a day behind your current date because, at your location, it was already the following day. 

I changed the log method to print the date with the current location, which should result in you seeing the date at your current time zone even though no changes to the actual date were made. Hope this helps!
